# Generated by Django 6.1 on 2026-08-26 05:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publicId', models.CharField(editable=False, max_length=20, unique=True)),
                ('inquiryId', models.CharField(blank=True, default='', max_length=20)),
                ('callerName', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=20)),
                ('category', models.CharField(choices=[('Service Quality', 'Service Quality'), ('Billing / Fees', 'Billing / Fees'), ('Auction Process', 'Auction Process'), ('Staff Conduct', 'Staff Conduct'), ('Technical Issue', 'Technical Issue'), ('Delivery / Item Condition', 'Delivery / Item Condition'), ('Other', 'Other')], max_length=40)),
                ('description', models.TextField()),
                ('department', models.CharField(choices=[('Call Center', 'Call Center'), ('Finance', 'Finance'), ('Auction Operations', 'Auction Operations'), ('IT Support', 'IT Support'), ('Logistics', 'Logistics'), ('Management', 'Management')], max_length=30)),
                ('priority', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Urgent', 'Urgent')], default='Medium', max_length=10)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Resolved', 'Resolved')], default='Open', max_length=10)),
                ('resolution', models.TextField(blank=True, default='')),
                ('resolutionDate', models.DateField(blank=True, null=True)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=60, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('isBuiltIn', models.BooleanField(default=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actionDate', models.DateTimeField(auto_now_add=True)),
                ('userRole', models.CharField(blank=True, default='', max_length=60)),
                ('action', models.CharField(max_length=255)),
                ('previousValue', models.CharField(blank=True, default='', max_length=150)),
                ('newValue', models.CharField(blank=True, default='', max_length=150)),
                ('reason', models.TextField(blank=True, default='')),
                ('ipAddress', models.GenericIPAddressField(blank=True, null=True)),
                ('performedBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-actionDate'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publicId', models.CharField(editable=False, max_length=20, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=10)),
                ('privileges', models.JSONField(blank=True, default=list)),
                ('lastPasswordChange', models.DateTimeField(blank=True, null=True)),
                ('lastUsernameChange', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='crm.role')),
            ],
        ),
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publicId', models.CharField(editable=False, max_length=20, unique=True)),
                ('callerName', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=20)),
                ('company', models.CharField(blank=True, default='', max_length=200)),
                ('auction', models.CharField(blank=True, default='', max_length=300)),
                ('batch', models.CharField(blank=True, default='', max_length=100)),
                ('category', models.CharField(choices=[('Auction Information', 'Auction Information'), ('Registration Support', 'Registration Support'), ('Bidder Registration', 'Bidder Registration'), ('Bid Submission', 'Bid Submission'), ('Processing Fee Inquiry', 'Processing Fee Inquiry'), ('Payment Inquiry', 'Payment Inquiry'), ('Visitation Appointment', 'Visitation Appointment'), ('Technical Support', 'Technical Support'), ('Complaint', 'Complaint'), ('General Inquiry', 'General Inquiry'), ('Other', 'Other')], max_length=40)),
                ('priority', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Urgent', 'Urgent')], default='Medium', max_length=10)),
                ('dateTime', models.DateTimeField()),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Assigned', 'Assigned'), ('Pending Follow-up', 'Pending Follow-up'), ('Waiting for Customer', 'Waiting for Customer'), ('Resolved', 'Resolved'), ('Closed', 'Closed'), ('With Manager', 'With Manager')], default='Open', max_length=25)),
                ('followUpDate', models.DateField(blank=True, null=True)),
                ('resolutionNotes', models.TextField(blank=True, default='')),
                ('resolvedDate', models.DateField(blank=True, null=True)),
                ('attachments', models.JSONField(blank=True, default=list)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inquiries', to='crm.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Followup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publicId', models.CharField(editable=False, max_length=20, unique=True)),
                ('callerName', models.CharField(max_length=150)),
                ('date', models.DateField()),
                ('reminder', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Satisfied', 'Satisfied'), ('Not Satisfied', 'Not Satisfied'), ('No Show', 'No Show')], default='Pending', max_length=15)),
                ('notes', models.TextField(blank=True, default='')),
                ('createdDate', models.DateField(auto_now_add=True)),
                ('company', models.CharField(blank=True, default='', max_length=200)),
                ('batch', models.CharField(blank=True, default='', max_length=100)),
                ('guideName', models.CharField(blank=True, default='', max_length=150)),
                ('assignedOperator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='followups', to='crm.employee')),
                ('inquiry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='followups', to='crm.inquiry')),
            ],
        ),
        migrations.CreateModel(
            name='Escalation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publicId', models.CharField(editable=False, max_length=20, unique=True)),
                ('callerName', models.CharField(max_length=150)),
                ('operatorName', models.CharField(max_length=150)),
                ('note', models.TextField()),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Resolved', 'Resolved')], default='Open', max_length=10)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('resolutionNote', models.TextField(blank=True, default='')),
                ('resolvedAt', models.DateTimeField(blank=True, null=True)),
                ('createdBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escalations_raised', to=settings.AUTH_USER_MODEL)),
                ('inquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escalations', to='crm.inquiry')),
            ],
        ),
        migrations.CreateModel(
            name='VisitSetup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publicId', models.CharField(editable=False, max_length=20, unique=True)),
                ('company', models.CharField(max_length=200)),
                ('batch', models.CharField(max_length=100)),
                ('date', models.CharField(blank=True, default='', max_length=100)),
                ('address', models.CharField(blank=True, default='', max_length=300)),
                ('items', models.TextField(blank=True, default='')),
                ('guideName', models.CharField(max_length=150)),
                ('guidePhone', models.CharField(blank=True, default='', max_length=20)),
                ('guideDays', models.JSONField(blank=True, default=list)),
                ('guideTimeFrom', models.TimeField(blank=True, null=True)),
                ('guideTimeTo', models.TimeField(blank=True, null=True)),
                ('createdDate', models.DateField(auto_now_add=True)),
                ('createdBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visit_setups', to='crm.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publicId', models.CharField(editable=False, max_length=20, unique=True)),
                ('auction', models.CharField(blank=True, default='', max_length=300)),
                ('visitorName', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=20)),
                ('company', models.CharField(blank=True, default='', max_length=200)),
                ('visitDate', models.DateField()),
                ('visitTime', models.TimeField()),
                ('status', models.CharField(choices=[('Requested', 'Requested'), ('Approved', 'Approved'), ('Confirmed', 'Confirmed'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled'), ('No Show', 'No Show')], default='Requested', max_length=15)),
                ('notes', models.TextField(blank=True, default='')),
                ('batch', models.CharField(blank=True, default='', max_length=100)),
                ('guideName', models.CharField(blank=True, default='', max_length=150)),
                ('guidePhone', models.CharField(blank=True, default='', max_length=20)),
                ('address', models.CharField(blank=True, default='', max_length=300)),
                ('items', models.TextField(blank=True, default='')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('assignedStaff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='crm.employee')),
                ('setup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='crm.visitsetup')),
            ],
        ),
    ]
