# Generated by Django 6.1 on 2026-08-26 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='defaultPrivileges',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
