# Generated by Django 6.1 on 2026-08-26 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_role_defaultprivileges'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
