# Generated by Django 6.1 on 2026-08-27 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_alter_employee_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='assignedStaff',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
