# Generated by Django 6.1 on 2026-08-31 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_alter_appointment_assignedstaff'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visitsetup',
            old_name='date',
            new_name='dateFrom',
        ),
        migrations.RemoveField(
            model_name='visitsetup',
            name='guideDays',
        ),
        migrations.AddField(
            model_name='visitsetup',
            name='dateTo',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
