# Generated by Django 6.1 on 2026-09-01 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_inquiryattachment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inquiry',
            name='attachments',
        ),
    ]
