# Generated by Django 6.1 on 2026-09-12 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_pushsubscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subjectType', models.CharField(max_length=20)),
                ('subjectId', models.CharField(max_length=20)),
                ('recipientRole', models.CharField(max_length=20)),
                ('recipientPhone', models.CharField(max_length=20)),
                ('messageBody', models.TextField()),
                ('status', models.CharField(max_length=20)),
                ('providerResponse', models.TextField(blank=True, default='')),
                ('sentAt', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-sentAt'],
            },
        ),
        migrations.CreateModel(
            name='PartyVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subjectType', models.CharField(choices=[('visitation', 'visitation'), ('pickup', 'pickup')], max_length=20)),
                ('subjectId', models.CharField(max_length=20)),
                ('visitorToken', models.CharField(max_length=64, unique=True)),
                ('guideToken', models.CharField(max_length=64, unique=True)),
                ('visitorCode', models.CharField(max_length=6)),
                ('guideCode', models.CharField(max_length=6)),
                ('visitorVerifiedAt', models.DateTimeField(blank=True, null=True)),
                ('guideVerifiedAt', models.DateTimeField(blank=True, null=True)),
                ('visitorVerifiedByIp', models.GenericIPAddressField(blank=True, null=True)),
                ('guideVerifiedByIp', models.GenericIPAddressField(blank=True, null=True)),
                ('expiresAt', models.DateTimeField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='appointment',
            name='mapsLink',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.CreateModel(
            name='Pickup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publicId', models.CharField(editable=False, max_length=20, unique=True)),
                ('winnerName', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=20)),
                ('auction', models.CharField(blank=True, default='', max_length=300)),
                ('itemDescription', models.TextField(blank=True, default='')),
                ('quantity', models.CharField(blank=True, default='', max_length=50)),
                ('paymentReference', models.CharField(blank=True, default='', max_length=100)),
                ('pickupDate', models.DateField()),
                ('pickupTime', models.TimeField()),
                ('guideName', models.CharField(blank=True, default='', max_length=150)),
                ('guidePhone', models.CharField(blank=True, default='', max_length=20)),
                ('address', models.CharField(blank=True, default='', max_length=300)),
                ('mapsLink', models.URLField(blank=True, default='')),
                ('status', models.CharField(choices=[('Scheduled', 'Scheduled'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled'), ('No Show', 'No Show')], default='Scheduled', max_length=15)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('createdBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pickups', to='crm.employee')),
            ],
        ),
    ]
