# Generated by Django 6.1 on 2026-09-13 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_notificationlog_partyverification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='quantity',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
