# Generated by Django 6.1 on 2026-09-30 17:48

import crm.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_appointment_quantity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='isCustom',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='followup',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='followups', to='crm.appointment'),
        ),
        migrations.AddField(
            model_name='visitsetup',
            name='mapsLink',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='mapsLink',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='visitDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='visitTime',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='visitorName',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='callerName',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='escalation',
            name='callerName',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='followup',
            name='callerName',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='callerName',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='category',
            field=models.CharField(choices=[('CPO', 'CPO'), ('Auction Information', 'Auction Information'), ('Registration Support', 'Registration Support'), ('Bidder Registration', 'Bidder Registration'), ('Bid Submission', 'Bid Submission'), ('Processing Fee Inquiry', 'Processing Fee Inquiry'), ('Payment Inquiry', 'Payment Inquiry'), ('Visitation Appointment', 'Visitation Appointment'), ('Technical Support', 'Technical Support'), ('Complaint', 'Complaint'), ('General Inquiry', 'General Inquiry'), ('Other', 'Other')], max_length=40),
        ),
        migrations.AlterField(
            model_name='inquiryattachment',
            name='file',
            field=models.FileField(upload_to=crm.models.inquiry_attachment_path),
        ),
        migrations.CreateModel(
            name='SavedLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=300)),
                ('addressKey', models.CharField(max_length=300, unique=True)),
                ('mapsLink', models.URLField(max_length=500)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('updatedBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
