# Generated by Django 6.1 on 2026-09-30 19:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0012_backfill_saved_locations'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PfmWinner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoiceNumber', models.CharField(max_length=60, unique=True)),
                ('bidderName', models.CharField(blank=True, default='', max_length=150)),
                ('bidderNameAmharic', models.CharField(blank=True, default='', max_length=150)),
                ('companyName', models.CharField(blank=True, default='', max_length=200)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.CharField(blank=True, default='', max_length=200)),
                ('auction', models.CharField(blank=True, default='', max_length=300)),
                ('lots', models.JSONField(blank=True, default=list)),
                ('lotsSummary', models.TextField(blank=True, default='')),
                ('amountPaid', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('verifiedAt', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('New', 'New'), ('Scheduled', 'Scheduled'), ('Skipped', 'Skipped')], default='New', max_length=10)),
                ('importedAt', models.DateTimeField(auto_now_add=True)),
                ('importedBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('pickup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pfm_winners', to='crm.pickup')),
            ],
            options={
                'ordering': ['-verifiedAt', '-importedAt'],
            },
        ),
    ]
