# Generated by Django 6.1 on 2026-10-01 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0013_pfm_winner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pickup',
            name='pickupDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pickup',
            name='pickupTime',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
