# Generated by Django 6.1 on 2026-10-03 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0015_remove_pickup_datetime'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['-createdAt'], name='crm_appoint_created_a982b8_idx'),
        ),
        migrations.AddIndex(
            model_name='followup',
            index=models.Index(fields=['status', 'date'], name='crm_followu_status_f48463_idx'),
        ),
        migrations.AddIndex(
            model_name='inquiry',
            index=models.Index(fields=['phone'], name='crm_inquiry_phone_376bc9_idx'),
        ),
        migrations.AddIndex(
            model_name='inquiry',
            index=models.Index(fields=['-dateTime'], name='crm_inquiry_dateTim_332fac_idx'),
        ),
    ]
