# Generated by Django 6.1 on 2026-10-04 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0016_add_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='partyverification',
            name='failedAttempts',
            field=models.IntegerField(default=0),
        ),
    ]
